### ISSUE TITLE
Data fixture (data.json) does not match the table schema

### ISSUE THREAD

**Issue by jbrucker** [jaybjackie/HungryMe#78]
When I use "manage.py loaddata data.json" it **fails** with a deserialization error:

```
raise FieldDoesNotExist(
django.core.exceptions.FieldDoesNotExist: Menu has no field named 'total_cooking_time'
```

Looks like you did not create all migrations, either:
```
  No migrations to apply.
  Your models in app(s): 'foods' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```

**Comment by jaybjackie** [comment]
The reason of failure when `manage.py` loaddata data.json because, datas in data.json file was an old models datas which doesn't match current model.

I will change data in data.json. I will also write more precise steps for installation.

For 
```
  No migrations to apply.
  Your models in app(s): 'foods' have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
 ```
  
 It will always says this message because, one of our models `foodofday` have update time attribute every second.
Anyway, I will write docs and maybe cover this steps in the instruction.

**Comment by jaybjackie** [comment]
By the way, sorry for delay response and didn't fix previous issues.
This week I was very busy for doing projects in other subjects.
Tonight I will follow up the previous issues and comments.

Thank you for having a look for our project.

**Comment by jaybjackie** [comment]
I will continue fixing tomorrow.

**Comment by jaybjackie** [comment]
From the PR #79, I have update the data in data.json file.
The problem occurred because, there was several change in Menu Models which is the core models for our project.
The schema was changed too. But data in data.json was old . Lead to problems when `manage.py loaddata data.json`.

I solved by `dump` new data in `data.json`.

I was thinking I should dump data for user data too. So, Others can `login with google`
or it was a thing I needed to do but I was clumsy forgot  about it.
:monocle_face:
